### ISSUE TITLE
Game does not open at all.

### ISSUE THREAD

**Issue by Daybroken0** [TerrariaCraft/Issues#104]
After downloading the official launcher and linking my account, I tried to open the game and after it downloaded the JVM it just stopped and gave me this error.

Failed to launch the knot!
java.lang.RuntimeException: java.nio.file.AccessDeniedException: E:\TerrariaCraft\jvm\bin\api-ms-win-core-console-l1-1-0.dll
        at org.zeith.terraria.launcher.GameIgniter.validateJVM(GameIgniter.java:301)
        at org.zeith.terraria.launcher.GameIgniter.startGame(GameIgniter.java:108)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.AccessDeniedException: E:\TerrariaCraft\jvm\bin\api-ms-win-core-console-l1-1-0.dll
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
        at java.nio.file.Files.deleteIfExists(Unknown Source)
        at java.nio.file.Files.copy(Unknown Source)
        at org.zeith.dwnsrc.ZoneIdentifierFile.downloadFile(ZoneIdentifierFile.java:32)
        at org.zeith.terraria.launcher.GameIgniter.validateJVM(GameIgniter.java:295)
        ... 2 more

I also tried using just the mod itself with the reccomended mods on the website but it never works and gives this error instead.

[13:45:40] [Client thread/WARN] [mixin]: Error loading class: com/zeitheron/hammercore/utils/base/Cast (java.lang.ClassNotFoundException: The specified class 'com.zeitheron.hammercore.utils.base.Cast' was not found) [13:45:40] [Client thread/ERROR] [LaunchWrapper]: Unable to launch java.lang.reflect.InvocationTargetException: null 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_351] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_351] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?] 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?] 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?] 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?] Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/Block 	at net.minecraftforge.registries.GameData.init(GameData.java:143) ~[GameData.class:?] 	at net.minecraftforge.registries.GameData.<clinit>(GameData.java:130) ~[GameData.class:?] 	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[qe.class:?] 	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:497) ~[ni.class:?] 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?] 	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?] 	... 9 more Caused by: java.lang.ClassNotFoundException: net.minecraft.block.Block 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?] 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_351] 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_351] 	at net.minecraftforge.registries.GameData.init(GameData.java:143) ~[GameData.class:?] 	at net.minecraftforge.registries.GameData.<clinit>(GameData.java:130) ~[GameData.class:?] 	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[qe.class:?] 	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:497) ~[ni.class:?] 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?] 	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?] 	... 9 more Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?] 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_351] 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_351] 	at net.minecraftforge.registries.GameData.init(GameData.java:143) ~[GameData.class:?] 	at net.minecraftforge.registries.GameData.<clinit>(GameData.java:130) ~[GameData.class:?] 	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[qe.class:?] 	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:497) ~[ni.class:?] 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?] 	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?] 	... 9 more Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: com.zeitheron.hammercore.utils.base.Cast 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:741) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:726) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:297) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar:?] 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?] 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_351] 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_351] 	at net.minecraftforge.registries.GameData.init(GameData.java:143) ~[GameData.class:?] 	at net.minecraftforge.registries.GameData.<clinit>(GameData.java:130) ~[GameData.class:?] 	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[qe.class:?] 	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:497) ~[ni.class:?] 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?] 	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?] 	... 9 more [13:45:40] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException [13:45:40] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49) [13:45:40] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source) [13:45:40] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source) [13:45:40] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source) Exception caught from launcher net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49) 	at java.lang.SecurityManager.checkExit(Unknown Source) 	at java.lang.Runtime.exit(Unknown Source) 	at java.lang.System.exit(Unknown Source) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) Exiting with ERROR Exception in thread "Client thread"  [13:45:40] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:76)

**Comment by Zeitheron** [comment]
AccessDeniedException means that the files were downloaded by another user, try installing the launcher into your appdata directory, and not in the root directory of a drive.
To get into the AppData, type Win key + R, and type in `%appdata%` and hit Enter. You should be in `/AppData/Roaming/` folder.
Try installing the launcher in there, and see if that helps.

As to the crash of a manual modpack, you did not install latest HammerLib for 1.12.2.

**Comment by Daybroken0** [comment]
Thank you for the reply. This has fixed both of my problems, I suppose that's what I get for being lazy!

**Comment by Zeitheron** [comment]
I'm glad it's all good!
