### ISSUE TITLE
[BUG] game crashed

### ISSUE THREAD

**Issue by dapangzi6969** [TerrariaCraft/Issues#118]
---- Minecraft Crash Report ----
// I blame Zeitheron.

Time: 2024-04-10 23:39:28 CST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from TerrariaCraft (terraria)
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
    at org.zeith.terraria.client.assets.cfs.base.IDataProvider.tryCreateInputStream(IDataProvider.java:25)
    at org.zeith.terraria.client.assets.cfs.CFS.readHeader(CFS.java:38)
    at org.zeith.terraria.client.assets.AssetDownloader.downloadAssets(AssetDownloader.java:73)
    at org.zeith.terraria.common.CommonProxy.construct(CommonProxy.java:84)
    at org.zeith.terraria.client.ClientProxy.construct(ClientProxy.java:131)
    at org.zeith.terraria.TerrariaCraft.construct(TerrariaCraft.java:153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4431)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
    at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
    at sun.security.ssl.Alert.createSSLException(Unknown Source)
    at sun.security.ssl.TransportContext.fatal(Unknown Source)
    at sun.security.ssl.TransportContext.fatal(Unknown Source)
    at sun.security.ssl.TransportContext.fatal(Unknown Source)
    at sun.security.ssl.SSLTransport.decode(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at java.net.HttpURLConnection.getResponseCode(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
    at com.zeitheron.hammercore.lib.zlib.web.HttpRequest.code(HttpRequest.java:1625)
    at com.zeitheron.hammercore.lib.zlib.web.HttpRequest.stream(HttpRequest.java:1965)
    at org.zeith.terraria.client.assets.cfs.url.URLDataProvider.crInput(URLDataProvider.java:52)
    at org.zeith.terraria.client.assets.cfs.base.IDataProvider.tryCreateInputStream(IDataProvider.java:22)
    ... 52 more
    Suppressed: java.net.SocketException: Connection reset by peer: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(Unknown Source)
        at java.net.SocketOutputStream.write(Unknown Source)
        at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(Unknown Source)
        ... 75 more
Caused by: java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(Unknown Source)
    at java.net.SocketInputStream.read(Unknown Source)
    at sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
    at sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
    at sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
    ... 72 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_291, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 101835240 bytes (97 MB) / 788529152 bytes (752 MB) up to 21474836480 bytes (20480 MB)
  JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx20480m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2860 20 mods loaded, 20 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID              | Version                    | Source                                         | Signature                                |
       |:----- |:--------------- |:-------------------------- |:---------------------------------------------- |:---------------------------------------- |
       | LC    | minecraft       | 1.12.2                     | minecraft.jar                                  | None                                     |
       | LC    | mcp             | 9.42                       | minecraft.jar                                  | None                                     |
       | LC    | FML             | 8.0.99.99                  | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LC    | forge           | 14.23.5.2860               | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LC    | cubicchunkscore | 1.12.2-0.0.1208.0-SNAPSHOT | minecraft.jar                                  | None                                     |
       | LC    | foamfixcore     | 7.7.4                      | minecraft.jar                                  | None                                     |
       | LC    | hammercore      | 12.2.49                    | HammerLib-1.12.2-12.2.49.jar                   | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LC    | lux             | 12.6.33                    | ColoredLux-1.12.2-12.6.33.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LC    | cubicchunks     | 1.12.2-0.0.1208.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar | None                                     |
       | LC    | foamfix         | @VERSION@                  | foamfix-0.10.15-1.12.2.jar                     | None                                     |
       | LC    | hammeranims     | 12.2.21                    | HammerAnimations-1.12.2-12.2.21.jar            | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LC    | mccue           | 12.4.10                    | McCue-1.12.2-12.4.10.jar                       | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LC    | musiclayer      | 12.2.22                    | MusicLayer-1.12.2-12.2.22.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LC    | nanfix          | Final                      | nanfix-final-absorbtion.jar                    | None                                     |
       | LC    | performant      | 1.12.2-1.5                 | performant-1.11.jar                            | None                                     |
       | LC    | spark           | 1.6.3                      | spark-forge.jar                                | None                                     |
       | LE    | terraria        | 12.6.1                     | TerrariaCraft-1.12.2-12.6.1.jar                | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | L     | tcrecipeview    | 6.0.1                      | TerrariaCraftRecipeViewer-1.12.2-6.0.1.jar     | None                                     |
       | L     | tcvm            | 6.0.1                      | TerrariaCraftVeinMiner-1.12.2-6.0.1.jar        | None                                     |
       | L     | vanillafix      | 1.0.10-150                 | VanillaFix-1.0.10-150.jar                      | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      HCASM (HammerLib-1.12.2-12.2.49.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar)
                                        io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
                                      TerrariaCraft Coremod (TerrariaCraft-1.12.2-12.6.1.jar)
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 536.23' Renderer: 'NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2'
  HammerCore Debug Information: Dependent Mods:
                                -Colored Lux (lux) @ 12.6.33
                                -HammerAnimations (hammeranims) @ 12.2.21
                                -Mc Cue (mccue) @ 12.4.10
                                -MusicLayer (musiclayer) @ 12.2.22
                                -TerrariaCraft (terraria) @ 12.6.1
  Suspected Mods: TerrariaCraft (terraria), HammerLib (hammercore)
  Launched Version: TerrariaCraft Official Modpack
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.23, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 16x AMD Ryzen 7 5800X 8-Core Processor

**Comment by dapangzi6969** [comment]
Uninstall Mcue don't work
