### ISSUE TITLE
Game crashes on startup, detailed crash report below [CRASH REPORT]

### ISSUE THREAD

**Issue by ZonaryMoth** [TerrariaCraft/Issues#119]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TerrariaCraft Coremod (TerrariaCraft-1.12.2-12.6.2.jar)
  HCASM (HammerLib-1.12.2-12.2.50.jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1271.0-SNAPSHOT-all.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 4/26/24 3:51 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from TerrariaCraft (terraria)
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.zeith.terraria.client.assets.cfs.base.IDataProvider.tryCreateInputStream(IDataProvider.java:25)
	at org.zeith.terraria.client.assets.cfs.CFS.readHeader(CFS.java:38)
	at org.zeith.terraria.client.assets.AssetDownloader.downloadAssets(AssetDownloader.java:73)
	at org.zeith.terraria.common.CommonProxy.construct(CommonProxy.java:88)
	at org.zeith.terraria.client.ClientProxy.construct(ClientProxy.java:131)
	at org.zeith.terraria.TerrariaCraft.construct(TerrariaCraft.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.zeitheron.hammercore.lib.zlib.web.HttpRequest.code(HttpRequest.java:1625)
	at com.zeitheron.hammercore.lib.zlib.web.HttpRequest.stream(HttpRequest.java:1965)
	at org.zeith.terraria.client.assets.cfs.url.URLDataProvider.crInput(URLDataProvider.java:52)
	at org.zeith.terraria.client.assets.cfs.base.IDataProvider.tryCreateInputStream(IDataProvider.java:22)
	... 46 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
	... 68 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 74 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 202699240 bytes (193 MB) / 1474822144 bytes (1406 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version                    | Source                                         | Signature                                |
	|:----- |:--------------- |:-------------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft       | 1.12.2                     | minecraft.jar                                  | None                                     |
	| LC    | mcp             | 9.42                       | minecraft.jar                                  | None                                     |
	| LC    | FML             | 8.0.99.99                  | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge           | 14.23.5.2860               | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | cubicchunkscore | 1.12.2-0.0.1271.0-SNAPSHOT | minecraft.jar                                  | None                                     |
	| LC    | cubicchunks     | 1.12.2-0.0.1271.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1271.0-SNAPSHOT-all.jar | None                                     |
	| LC    | hammercore      | 12.2.50                    | HammerLib-1.12.2-12.2.50.jar                   | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LC    | hammeranims     | 12.2.26                    | HammerAnimations-1.12.2-12.2.26.jar            | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LC    | musiclayer      | 12.2.22                    | MusicLayer-1.12.2-12.2.22.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LE    | terraria        | 12.6.2                     | TerrariaCraft-1.12.2-12.6.2.jar                | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |

	Loaded coremods (and transformers): 
TerrariaCraft Coremod (TerrariaCraft-1.12.2-12.6.2.jar)
  
HCASM (HammerLib-1.12.2-12.2.50.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1271.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.AddEmptyConstructorToChunk
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 552.12' Renderer: 'NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2'
	HammerCore Debug Information: 
		Dependent Mods:
			-HammerAnimations (hammeranims) @ 12.2.26
			-MusicLayer (musiclayer) @ 12.2.22
			-TerrariaCraft (terraria) @ 12.
			
			
Any help would be appreciated, i just want to be able to enjoy the mod.

**Comment by Zeitheron** [comment]
Use our launcher.
