### ISSUE TITLE
[BUG] Crashing on startup only on Linux

### ISSUE THREAD

**Issue by NIICKTCHUNS** [TerrariaCraft/Issues#140]
I always play my games here on Linux and never had any problems, idk why this is happening but is probably caused by MC Cue, is MC Cue that important for the mod? I installed from SKLauncher (with my original account connected) on Windows and Linux and only here its crashing...

Steps to reproduce this is really just install it from SKLauncher...

My specs and system are:
Arch Linux with Linux 6.11.9
CPU: i5-9400F
GPU: RX 7600
24GB of RAM
Java: openjdk 23 2024-09-17 | OpenJDK Runtime Environment (build 23) |OpenJDK 64-Bit Server VM (build 23, mixed mode, sharing)

![image](https://github.com/user-attachments/assets/42c67cc4-0615-46cd-a379-1759336f988b)

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-11-20 20:11:51 BRST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mc Cue (mccue)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.zeith.mccue.client.sdk.corsair.icue.jna.CUESDKLibrary
    at org.zeith.mccue.client.sdk.corsair.icue.CueSDK.<init>(CueSDK.java:28)
    at org.zeith.mccue.client.ClientProxy.lambda$a$0(ClientProxy.java:89)
    at org.zeith.mccue.api.sdk.RgbSdkRegistry.init(RgbSdkRegistry.java:28)
    at org.zeith.mccue.client.ClientProxy.b(ClientProxy.java:115)
    at org.zeith.mccue.McCue.pre(McCue.java:59)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4431)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 6.11.9-arch1-1
  Java Version: 1.8.0_202, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 695324360 bytes (663 MB) / 1610612736 bytes (1536 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 7 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx8192m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2860 20 mods loaded, 20 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID              | Version                    | Source                                         | Signature                                |
       |:----- |:--------------- |:-------------------------- |:---------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft       | 1.12.2                     | minecraft.jar                                  | None                                     |
       | LCH   | mcp             | 9.42                       | minecraft.jar                                  | None                                     |
       | LCH   | FML             | 8.0.99.99                  | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge           | 14.23.5.2860               | forge-1.12.2-14.23.5.2860.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | cubicchunkscore | 1.12.2-0.0.1208.0-SNAPSHOT | minecraft.jar                                  | None                                     |
       | LCH   | foamfixcore     | 7.7.4                      | minecraft.jar                                  | None                                     |
       | LCH   | hammercore      | 12.2.50                    | HammerLib-1.12.2-12.2.50.jar                   | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCH   | lux             | 12.6.33                    | ColoredLux-1.12.2-12.6.33.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCH   | cubicchunks     | 1.12.2-0.0.1208.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar | None                                     |
       | LCH   | foamfix         | @VERSION@                  | foamfix-0.10.15-1.12.2.jar                     | None                                     |
       | LCH   | hammeranims     | 12.2.25.1                  | HammerAnimations-1.12.2-12.2.25.1.jar          | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCE   | mccue           | 12.4.10                    | McCue-1.12.2-12.4.10.jar                       | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LC    | musiclayer      | 12.2.22                    | MusicLayer-1.12.2-12.2.22.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LC    | nanfix          | Final                      | nanfix-final-absorbtion.jar                    | None                                     |
       | LC    | performant      | 1.12.2-1.5                 | performant-1.11.jar                            | None                                     |
       | LC    | spark           | 1.6.3                      | spark-forge.jar                                | None                                     |
       | LC    | terraria        | 12.6.2                     | TerrariaCraft-1.12.2-12.6.2.jar                | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LC    | tcrecipeview    | 6.0.2                      | TerrariaCraftRecipeViewer-1.12.2-6.0.2.jar     | None                                     |
       | LC    | tcvm            | 6.0.1                      | TerrariaCraftVeinMiner-1.12.2-6.0.1.jar        | None                                     |
       | LC    | vanillafix      | 1.0.10-150                 | VanillaFix-1.0.10-150.jar                      | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar)
                                        io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
                                      TerrariaCraft Coremod (TerrariaCraft-1.12.2-12.6.2.jar)
                                        
                                      HCASM (HammerLib-1.12.2-12.2.50.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
  GL info: ' Vendor: 'AMD' Version: '4.6 (Compatibility Profile) Mesa 24.2.7-arch1.1' Renderer: 'AMD Radeon RX 7600 (radeonsi, navi33, LLVM 18.1.8, DRM 3.59, 6.11.9-arch1-1)'
  HammerCore Debug Information: Dependent Mods:
                                -Colored Lux (lux) @ 12.6.33
                                -HammerAnimations (hammeranims) @ 12.2.25.1
                                -Mc Cue (mccue) @ 12.4.10
                                -MusicLayer (musiclayer) @ 12.2.22
                                -TerrariaCraft (terraria) @ 12.6.2
  CubicChunks WorldGen Hang Watchdog samples: (no data)
  Suspected Mods: Mc Cue (mccue)
  Launched Version: 1.12.2-forge-14.23.5.2860
  LWJGL: 2.9.4
  OpenGL: AMD Radeon RX 7600 (radeonsi, navi33, LLVM 18.1.8, DRM 3.59, 6.11.9-arch1-1) GL version 4.6 (Compatibility Profile) Mesa 24.2.7-arch1.1, AMD
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 6x Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
```

**Comment by NIICKTCHUNS** [comment]
A complement to the info that I already gave, I also tried with the official Minecraft launcher and downloaded the bundle from the site, the launcher returns the error 255...

![image](https://github.com/user-attachments/assets/c0e78d66-8dca-4a61-af1e-79864848283a)

**Comment by Zeitheron** [comment]
Uninstall McCue. it only works under Windows.
