### ISSUE TITLE
The Game Crashes on Startup

### ISSUE THREAD

**Issue by Jakobtheraddude** [TerrariaCraft/Issues#23]
I don't have optifine on and I have all the dependencies this is the error log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TerrariaCraftCoremod (TerrariaCraft-1.12.2-12.3.21.jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1161.0-SNAPSHOT-all.jar)
  HCASM (HammerLib-1.12.2-2.0.6.26.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 1/8/21 5:58 PM
Description: Initializing game

java.lang.IllegalStateException: glGenLists returned an ID of 0 for a count of 1, GL error (1282): Invalid operation
	at net.minecraft.client.renderer.GLAllocation.func_74526_a(SourceFile:27)
	at net.minecraft.client.model.ModelBoat.<init>(SourceFile:15)
	at net.minecraft.client.renderer.entity.RenderBoat.<init>(SourceFile:20)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:216)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.GLAllocation.func_74526_a(SourceFile:27)
	at net.minecraft.client.model.ModelBoat.<init>(SourceFile:15)
	at net.minecraft.client.renderer.entity.RenderBoat.<init>(SourceFile:20)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:216)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1473254720 bytes (1405 MB) / 2147483648 bytes (2048 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version                    | Source                                         | Signature                                |
	|:----- |:--------------- |:-------------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft       | 1.12.2                     | minecraft.jar                                  | None                                     |
	| LCH   | mcp             | 9.42                       | minecraft.jar                                  | None                                     |
	| LCH   | FML             | 8.0.99.99                  | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
	| LCH   | forge           | 14.23.5.2847               | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
	| LCH   | cubicchunkscore | 1.12.2-0.0.1161.0-SNAPSHOT | minecraft.jar                                  | None                                     |
	| LCH   | hammercore      | 2.0.6.26                   | HammerLib-1.12.2-2.0.6.26.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCH   | lux             | 12.4.18                    | ColoredLux-1.12.2-12.4.18.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCH   | cubicchunks     | 1.12.2-0.0.1161.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1161.0-SNAPSHOT-all.jar | None                                     |
	| LCH   | mccue           | 1r                         | McCue-1.12.2-12.3.6.jar                        | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCH   | musiclayer      | 12.3.21                    | MusicLayer-1.12.2-12.3.21.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCH   | terraria        | 12.3.21                    | TerrariaCraft-1.12.2-12.3.21.jar               | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |

	Loaded coremods (and transformers): 
TerrariaCraftCoremod (TerrariaCraft-1.12.2-12.3.21.jar)
  tk.zeitheron.terraria.asm.TerrariaCraftASM
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1161.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
HCASM (HammerLib-1.12.2-2.0.6.26.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	GL info: ' Vendor: 'null' Version: 'null' Renderer: 'null'
	HammerCore Debug Information: 
		Dependent Mods:
			-Colored Lux (lux) @ 12.4.18
			-Mc Cue (mccue) @ 1r
			-Music Layer (musiclayer) @ 12.3.21
			-Terraria Craft (terraria) @ 12.3.21

	CubicChunks WorldGen Hang Watchdog samples: (no data)
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: null GL version null, null
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz

**Comment by Zeitheron** [comment]
Haven't seen that one before nor could replicate... try downgrading cubic chunks to 1055 build, might help(?)
