### ISSUE TITLE
[BUG] crash after launch

### ISSUE THREAD

**Issue by senballpl** [TerrariaCraft/Issues#35]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
  TerrariaCraftCoremod (TerrariaCraft-1.12.2-12.3.23.jar)
  HCASM (HammerLib-1.12.2-2.0.6.26.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/11/21 11:35 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Terraria Craft (terraria)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.zeitheron.mccue.client.sdk.logitech.lew.jna.LogiLedLibrary
  at tk.zeitheron.terraria.compat.mccue.rgb.logitech.LogitechDeviceGroup.initialize(LogitechDeviceGroup.java:35)
  at tk.zeitheron.terraria.compat.mccue.rgb.RgbDeviceGroup.enable(RgbDeviceGroup.java:15)
  at tk.zeitheron.terraria.compat.mccue.rgb.ChromaEngine.enableDeviceGroup(ChromaEngine.java:66)
  at tk.zeitheron.terraria.compat.mccue.ChromaInitializer.addDevices(ChromaInitializer.java:56)
  at tk.zeitheron.terraria.compat.mccue.ChromaInitializer.load(ChromaInitializer.java:63)
  at tk.zeitheron.terraria.compat.mccue.McCueCompat.init(McCueCompat.java:34)
  at java.util.ArrayList.forEach(ArrayList.java:1259)
  at tk.zeitheron.terraria.TerrariaCraft.init(TerrariaCraft.java:326)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
  at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
  at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
  at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
  at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
  at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
  at com.google.common.eventbus.EventBus.post(EventBus.java:217)
  at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
  at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
  at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
  at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
  at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
  at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
  at com.google.common.eventbus.EventBus.post(EventBus.java:217)
  at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
  at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
  at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
  at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
  at net.minecraft.client.main.Main.main(SourceFile:123)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
  at crystallauncher.MineClient.start(MineClient.java:188)
  at crystallauncher.MineClient.main(MineClient.java:33)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_271, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1002504424 bytes (956 MB) / 1811939328 bytes (1728 MB) up to 1811939328 bytes (1728 MB)
  JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1711M -Xms1711M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 11 mods loaded, 11 mods active
  States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

  | State | ID              | Version                    | Source                                         | Signature                                |
  |:----- |:--------------- |:-------------------------- |:---------------------------------------------- |:---------------------------------------- |
  | LCHI  | minecraft       | 1.12.2                     | minecraft.jar                                  | None                                     |
  | LCHI  | mcp             | 9.42                       | minecraft.jar                                  | None                                     |
  | LCHI  | FML             | 8.0.99.99                  | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
  | LCHI  | forge           | 14.23.5.2847               | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
  | LCHI  | cubicchunkscore | 1.12.2-0.0.1055.0-SNAPSHOT | minecraft.jar                                  | None                                     |
  | LCHI  | hammercore      | 2.0.6.26                   | HammerLib-1.12.2-2.0.6.26.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
  | LCHI  | lux             | 12.4.18                    | ColoredLux-1.12.2-12.4.18.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
  | LCHI  | cubicchunks     | 1.12.2-0.0.1055.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar | None                                     |
  | LCHI  | mccue           | 1r                         | McCue-1.12.2-12.3.6.jar                        | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
  | LCHI  | musiclayer      | 12.3.21                    | MusicLayer-1.12.2-12.3.21.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
  | LCHE  | terraria        | 12.3.23                    | TerrariaCraft-1.12.2-12.3.23.jar               | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |

  Loaded coremods (and transformers): 
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
TerrariaCraftCoremod (TerrariaCraft-1.12.2-12.3.23.jar)
  tk.zeitheron.terraria.asm.TerrariaCraftASM
HCASM (HammerLib-1.12.2-2.0.6.26.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GT 610/PCIe/SSE2'
  HammerCore Debug Information: 
    Dependent Mods:
      -Colored Lux (lux) @ 12.4.18
      -Mc Cue (mccue) @ 1r
      -Music Layer (musiclayer) @ 12.3.21
      -Terraria Craft (terraria) @ 12.3.23

  CubicChunks WorldGen Hang Watchdog samples: (no data)
[11:35:45] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\48508\Downloads\prywatne\Crystal-Launcher\instances\u.terrariacraft\.minecraft\crash-reports\crash-2021-06-11_11.35.45-client.txt

sorry but idk what happen

**Comment by Zeitheron** [comment]
Downgrade or uninstall Corsair McCue
