### ISSUE TITLE
This is happing before I can load in the main menu it happens while loading the mod. 

### ISSUE THREAD

**Issue by Zanegottem1** [TerrariaCraft/Issues#48]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  HCASM (HammerLib-1.12.2-2.0.6.28.jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1184.0-SNAPSHOT-all.jar)
  TerrariaCraftCoremod (TerrariaCraft-1.12.2-12.4.25.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 10/16/21 6:42 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Terraria Craft (terraria)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.zeith.mccue.client.sdk.logitech.lew.jna.LogiLedLibrary
	at org.zeith.terraria.compat.mccue.rgb.logitech.LogitechDeviceGroup.initialize(LogitechDeviceGroup.java:35)
	at org.zeith.terraria.compat.mccue.rgb.RgbDeviceGroup.enable(RgbDeviceGroup.java:15)
	at org.zeith.terraria.compat.mccue.rgb.ChromaEngine.enableDeviceGroup(ChromaEngine.java:64)
	at org.zeith.terraria.compat.mccue.ChromaInitializer.addDevices(ChromaInitializer.java:55)
	at org.zeith.terraria.compat.mccue.ChromaInitializer.load(ChromaInitializer.java:62)
	at org.zeith.terraria.compat.mccue.McCueCompat.init(McCueCompat.java:36)
	at org.zeith.terraria.TerrariaCraft$$Lambda$952/941039802.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.zeith.terraria.TerrariaCraft.init(TerrariaCraft.java:306)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 391577032 bytes (373 MB) / 1964507136 bytes (1873 MB) up to 6532104192 bytes (6229 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7008m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version                    | Source                                         | Signature                                |
	|:----- |:--------------- |:-------------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft       | 1.12.2                     | minecraft.jar                                  | None                                     |
	| LCHI  | mcp             | 9.42                       | minecraft.jar                                  | None                                     |
	| LCHI  | FML             | 8.0.99.99                  | forge-1.12.2-14.23.5.2855.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge           | 14.23.5.2855               | forge-1.12.2-14.23.5.2855.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | cubicchunkscore | 1.12.2-0.0.1184.0-SNAPSHOT | minecraft.jar                                  | None                                     |
	| LCHI  | hammercore      | 2.0.6.28                   | HammerLib-1.12.2-2.0.6.28.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHI  | lux             | 12.6.25                    | ColoredLux-1.12.2-12.6.25.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHI  | cubicchunks     | 1.12.2-0.0.1184.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1184.0-SNAPSHOT-all.jar | None                                     |
	| LCHI  | mccue           | 12.4.8                     | McCue-1.12.2-12.4.8.jar                        | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHI  | musiclayer      | 12.3.21                    | MusicLayer-1.12.2-12.3.21.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHE  | terraria        | 12.4.25                    | TerrariaCraft-1.12.2-12.4.25.jar               | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |

	Loaded coremods (and transformers): 
HCASM (HammerLib-1.12.2-2.0.6.28.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1184.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
TerrariaCraftCoremod (TerrariaCraft-1.12.2-12.4.25.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 457.30' Renderer: 'Quadro P5000/PCIe/SSE2'
	HammerCore Debug Information: 
		Dependent Mods:
			-Colored Lux (lux) @ 12.6.25
			-Mc Cue (mccue) @ 12.4.8
			-Music Layer (musiclayer) @ 12.3.21
			-Terraria Craft (terraria) @ 12.4.25

	CubicChunks WorldGen Hang Watchdog samples: (no data)

**Comment by Zeitheron** [comment]
Uninstall Corsair McCue.
