### ISSUE TITLE
[BUG] Cant join the server, and the mod failed loading.

### ISSUE THREAD

**Issue by olinktv** [TerrariaCraft/Issues#78]
Server log:
[18:23:36] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
--
449 | net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Terraria Craft (terraria)
450 |  
451 | Caused by: java.lang.NoSuchFieldError: CLIENT_DATA
452 | at org.zeith.terraria.common.data.DataLoaderTC.<clinit>(DataLoaderTC.java:46) ~[TerrariaCraft-1.12.2-12.5.32.jar:?]
453 | at org.zeith.terraria.TerrariaCraft.serverStarting(TerrariaCraft.java:330) ~[TerrariaCraft-1.12.2-12.5.32.jar:?]
454 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
455 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
456 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
457 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
458 | at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge.jar:?]
459 | at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
460 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
461 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
462 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
463 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
464 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
465 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
466 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
467 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
468 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
469 | at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[LoadController.class:?]
470 | at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[LoadController.class:?]
471 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
472 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
473 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
474 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
475 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
476 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
477 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
478 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
479 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
480 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
481 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
482 | at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
483 | at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:797) ~[Loader.class:?]
484 | at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:297) ~[FMLCommonHandler.class:?]
485 | at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:307) ~[nz.class:?]
486 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
487 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
488 | [18:23:36] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /server/./crash-reports/crash-2022-03-01_18.23.36-server.txt
493 | [18:23:39] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.WorldEvent$Save@4360da18:
494 | java.lang.NoClassDefFoundError: Could not initialize class org.zeith.terraria.common.data.DataLoaderTC
495 | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_98_DataLoaderTC_saveWorld_Save.invoke(.dynamic) ~[?:?]
496 | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
497 | at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
498 | at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1008) [oo.class:?]
499 | at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
500 | at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:446) [MinecraftServer.class:?]
501 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579) [MinecraftServer.class:?]
502 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
503 | [18:23:39] [Server thread/ERROR] [FML]: Index: 4 Listeners:
504 | [18:23:39] [Server thread/ERROR] [FML]: 0: HIGHEST
505 | [18:23:39] [Server thread/ERROR] [FML]: 1: ASM: net.minecraftforge.common.ForgeInternalHandler@4702aba5 onDimensionSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
506 | [18:23:39] [Server thread/ERROR] [FML]: 2: NORMAL
507 | [18:23:39] [Server thread/ERROR] [FML]: 3: ASM: class com.zeitheron.hammercore.world.WorldGenHelper worldSaveEvt(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
508 | [18:23:39] [Server thread/ERROR] [FML]: 4: ASM: class org.zeith.terraria.common.data.DataLoaderTC saveWorld(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
509 | [18:23:39] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Exception stopping the server
510 | java.lang.NoClassDefFoundError: Could not initialize class org.zeith.terraria.common.data.DataLoaderTC
511 | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_98_DataLoaderTC_saveWorld_Save.invoke(.dynamic) ~[?:?]
512 | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
513 | at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
514 | at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1008) ~[oo.class:?]
515 | at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) ~[MinecraftServer.class:?]
516 | at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:446) ~[MinecraftServer.class:?]
517 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579) [MinecraftServer.class:?]
518 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

</body>
</html>[18:23:36] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Terraria Craft (terraria)

Caused by: java.lang.NoSuchFieldError: CLIENT_DATA
	at org.zeith.terraria.common.data.DataLoaderTC.<clinit>(DataLoaderTC.java:46) ~[TerrariaCraft-1.12.2-12.5.32.jar:?]
	at org.zeith.terraria.TerrariaCraft.serverStarting(TerrariaCraft.java:330) ~[TerrariaCraft-1.12.2-12.5.32.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge.jar:?]
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:797) ~[Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:297) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:307) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[18:23:36] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /server/./crash-reports/crash-2022-03-01_18.23.36-server.txt
[18:23:36] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[18:23:36] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[18:23:36] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[18:23:36] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/overworld
[18:23:39] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.WorldEvent$Save@4360da18:
java.lang.NoClassDefFoundError: Could not initialize class org.zeith.terraria.common.data.DataLoaderTC
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_98_DataLoaderTC_saveWorld_Save.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1008) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:446) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[18:23:39] [Server thread/ERROR] [FML]: Index: 4 Listeners:
[18:23:39] [Server thread/ERROR] [FML]: 0: HIGHEST
[18:23:39] [Server thread/ERROR] [FML]: 1: ASM: net.minecraftforge.common.ForgeInternalHandler@[470](https://aternos.org/log/#L470)2aba5 onDimensionSave(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
[18:23:39] [Server thread/ERROR] [FML]: 2: NORMAL
[18:23:39] [Server thread/ERROR] [FML]: 3: ASM: class com.zeitheron.hammercore.world.WorldGenHelper worldSaveEvt(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
[18:23:39] [Server thread/ERROR] [FML]: 4: ASM: class org.zeith.terraria.common.data.DataLoaderTC saveWorld(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
[18:23:39] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Exception stopping the server
java.lang.NoClassDefFoundError: Could not initialize class org.zeith.terraria.common.data.DataLoaderTC
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_98_DataLoaderTC_saveWorld_Save.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1008) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:446) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Comment by ApplY3D** [comment]
The same. Can't start server with minecraft docker server:

```bash
docker run -d -it -p 25565:25565 -e EULA=TRUE -e TYPE=AUTO_CURSEFORGE -e CF_SLUG=terraria-craft-pack -e CF_MODPACK_ZIP="/modpacks/Terraria+Craft+Pack-12.5.32.zip" -e MEMORY=7G -e CF_API_KEY='$' -v ./data:/data -v ./modpacks:/modpacks:ro  itzg/minecraft-server:java8-multiarch
```
