### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AlbinoPea** [TerrariaCraft/Issues#9]
Hello my game keeps crashing to something here is the report. Thank you!
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2020-07-01 18:07:08 NZST
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinTransformer from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(Loader.java:1131)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 8.1 (amd64) version 6.3
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 499279848 bytes (476 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F4 20 mods loaded, 20 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                | Version                    | Source                                             | Signature |
       |:----- |:----------------- |:-------------------------- |:-------------------------------------------------- |:--------- |
       | L     | minecraft         | 1.12.2                     | minecraft.jar                                      | None      |
       | L     | mcp               | 9.42                       | minecraft.jar                                      | None      |
       | L     | FML               | 8.0.99.99                  | forge-1.12.2-14.23.5.2847.jar                      | None      |
       | L     | forge             | 14.23.5.2847               | forge-1.12.2-14.23.5.2847.jar                      | None      |
       | L     | foamfixcore       | 7.7.4                      | minecraft.jar                                      | None      |
       | L     | cubicchunkscore   | 1.12.2-0.0.1055.0-SNAPSHOT | minecraft.jar                                      | None      |
       | L     | chunkanimator     | 1.2                        | ChunkAnimator-MC1.12-1.2.jar                       | None      |
       | L     | cleanview         | 1.12.2-v1c                 | CleanView-1.12.2-v1c.jar                           | None      |
       | L     | clumps            | 3.1.2                      | Clumps-3.1.2.jar                                   | None      |
       | L     | cubicchunks       | 1.12.2-0.0.1055.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all (1).jar | None      |
       | L     | cubicgen          | 1.12.2-0.0.126.0-SNAPSHOT  | CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar    | None      |
       | L     | foamfix           | 0.10.8-1.12.2              | foamfix-0.10.8-1.12.2.jar                          | None      |
       | L     | hammercore        | 2.0.6.19                   | HammerLib-1.12.2-2.0.6.19.jar                      | None      |
       | L     | musiclayer        | 12.2.20                    | MusicLayer-1.12.2-12.2.20.jar                      | None      |
       | L     | nonausea          | 1.0                        | NoNausea-MC1.12-1.0.jar                            | None      |
       | L     | surge             | 2.0.77                     | Surge-1.12.2-2.0.77.jar                            | None      |
       | L     | terraria          | 12.2.15                    | TerrariaCraft-1.12.2-12.2.15 (1).jar               | None      |
       | L     | texfix            | 4.0                        | TexFix+V-1.12-4.0.jar                              | None      |
       | L     | vanillafix        | 1.0.10-SNAPSHOT            | VanillaFix-1.0.10-99.jar                           | None      |
       | L     | phosphor-lighting | 1.12.2-0.2.6               | phosphor-1.12.2-0.2.6+build50-universal.jar        | None      |
  Loaded coremods (and transformers): Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.8-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      MusicLayerCore (MusicLayer-1.12.2-12.2.20.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      HCASM (HammerLib-1.12.2-2.0.6.19.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      LoadingPlugin (NoNausea-MC1.12-1.0.jar)
                                        lumien.nonausea.asm.ClassTransformer
                                      CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all (1).jar)
                                        io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
                                      TerrariaCraftCoremod (TerrariaCraft-1.12.2-12.2.15 (1).jar)
                                        tk.zeitheron.terraria.asm.TerrariaCraftASM
                                      CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar)
                                        io.github.opencubicchunks.cubicchunks.cubicgen.asm.coremod.MapGenStrongholdCubicConstructorTransform
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.12422 Compatibility Profile Context 13.152.0.0' Renderer: 'AMD Radeon HD 8670A'
  Suspected Mods: Unknown
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: AMD Radeon HD 8670A GL version 4.2.12422 Compatibility Profile Context 13.152.0.0, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: No
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Bare+Bones+1.11-1.12.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i3-3227U CPU @ 1.90GHz

**Comment by AlbinoPea** [comment]
thinking about it, does this have to do anything with a folder in .minecraft called terraria? if so I actually deleted it idk why and if correct is there a way to get the folder. Thank you.

**Comment by AlbinoPea** [comment]
no need for help anymore
